# Generated by Django 4.2.16 on 2025-02-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("check", "0009_alter_problem_problem_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="problem_slug",
            field=models.CharField(max_length=256),
        ),
    ]
